name: deploy

on:
  push:
    branches: [ "main" ]

jobs:
  terraform:
    name: Deploy
    runs-on: ubuntu-20.04
    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.2.4

    - name: Lint
      working-directory: .
      run: terraform fmt -check

    - name: Setup AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: sa-east-1
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Initialize Terraform
      working-directory: .
      run: terraform init -input=false          

    - name: Plan Terraform
      id: plan
      working-directory: .
      run: |
        terraform plan -input=false -no-color -out=tfplan \
        && terraform show -no-color tfplan          

    - name: Apply Terraform
      if: steps.plan.outcome == 'success'
      id: apply
      working-directory: .
      run: |
        terraform apply \
          -input=false \
          -no-color \
          tfplan